import 'dart:io';

import 'package:csv/csv.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../transactions/transactions_repository.dart';

class ReportSummary {
  ReportSummary({required this.totalIncome, required this.totalExpense});

  final num totalIncome;
  final num totalExpense;

  num get net => totalIncome - totalExpense;

  factory ReportSummary.fromTransactions(List<TransactionRecord> transactions) {
    num income = 0;
    num expense = 0;
    for (final t in transactions) {
      if (t.type == 'income') {
        income += t.amount;
      } else if (t.type == 'expense') {
        expense += t.amount;
      }
    }
    return ReportSummary(totalIncome: income, totalExpense: expense);
  }
}

/// Generates real export files from real transaction data — every row here
/// is a real transaction the export was asked to include, nothing summarized
/// or invented. Only exports what's actually passed in.
class ReportExportService {
  static String _formatDate(DateTime date) =>
      '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';

  static Future<File> exportCsv({
    required List<TransactionRecord> transactions,
    required String fileNamePrefix,
  }) async {
    final rows = <List<dynamic>>[
      ['Date', 'Type', 'Category', 'Description', 'Merchant', 'Payment Method', 'Amount', 'Currency'],
      for (final t in transactions)
        [
          _formatDate(t.transactionDate),
          t.type,
          t.categoryName ?? '',
          t.description ?? '',
          t.merchant ?? '',
          t.paymentMethod ?? '',
          t.amount,
          t.currency,
        ],
    ];

    final csvString = const ListToCsvConverter().convert(rows);
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/${fileNamePrefix}_${DateTime.now().millisecondsSinceEpoch}.csv');
    return file.writeAsString(csvString);
  }

  static Future<File> exportPdf({
    required List<TransactionRecord> transactions,
    required ReportSummary summary,
    required String currency,
    required String title,
    required String periodLabel,
    required String fileNamePrefix,
  }) async {
    final doc = pw.Document();

    String money(num value) => '$currency ${value.toStringAsFixed(2)}';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(level: 0, text: title),
          pw.Text(periodLabel, style: const pw.TextStyle(color: PdfColors.grey700)),
          pw.SizedBox(height: 16),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Total income: ${money(summary.totalIncome)}'),
              pw.Text('Total expenses: ${money(summary.totalExpense)}'),
              pw.Text('Net: ${money(summary.net)}'),
            ],
          ),
          pw.SizedBox(height: 16),
          if (transactions.isEmpty)
            pw.Text('No transactions in this period.')
          else
            pw.Table.fromTextArray(
              headers: ['Date', 'Type', 'Category', 'Description', 'Amount'],
              data: [
                for (final t in transactions)
                  [
                    _formatDate(t.transactionDate),
                    t.type,
                    t.categoryName ?? '',
                    t.description ?? '',
                    money(t.amount),
                  ],
              ],
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              cellAlignment: pw.Alignment.centerLeft,
              cellAlignments: {4: pw.Alignment.centerRight},
            ),
          pw.SizedBox(height: 20),
          pw.Text(
            'Generated by PesaPlan on ${_formatDate(DateTime.now())}. For personal record-keeping.',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/${fileNamePrefix}_${DateTime.now().millisecondsSinceEpoch}.pdf');
    return file.writeAsBytes(await doc.save());
  }
}
